export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "Nitin Akuch",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "Amit Kadam",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "Akshay Katle",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "Nitin Shinde",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "Anand Birajdar",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "Mukesh Kshirsagar",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "Satish Kumthekar",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "Swapnil Surywanshi",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "Akshay Koli",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "Ganesh Deokate",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
];
