export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpg",
    username: "Nitin Akuch",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpg",
    username: "Amit Kadam",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpg",
    username: "Akshay Katle",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpg",
    username: "Nitin Shinde",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpg",
    username: "Anand Birajdar",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpg",
    username: "Mukesh Kshirsagar",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpg",
    username: "Satish Kumthekar",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpg",
    username: "Swapnil Surywanshi",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpg",
    username: "Akshay Koli",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpg",
    username: "Ganesh Deokate",
  },
];
export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/1.png",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/2.png",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/3.png",
    date: "5 mins ago",
    userId: 3,
    like: 32,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/4.jpg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/5.png",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/6.png",
    date: "5 mins ago",
    userId: 6,
    like: 32,
    comment: 9,
  },
  {
    id: 7,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/7.jpg",
    date: "5 mins ago",
    userId: 7,
    like: 32,
    comment: 9,
  },
  {
    id: 8,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/8.jpg",
    date: "5 mins ago",
    userId: 8,
    like: 32,
    comment: 9,
  },
  {
    id: 9,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/9.jpg",
    date: "5 mins ago",
    userId: 9,
    like: 32,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love For All, Hatred For None.",
    photo: "assets/post/10.png",
    date: "5 mins ago",
    userId: 10,
    like: 32,
    comment: 9,
  },
];
